# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(-48, 0, 1296, 687))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.voltageReadingField_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.voltageReadingField_ch1.setObjectName("voltageReadingField_ch1")
        self.gridLayout_2.addWidget(self.voltageReadingField_ch1, 5, 3, 1, 1)
        self.ovpVolLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelS_ch3.setObjectName("ovpVolLabelS_ch3")
        self.gridLayout_2.addWidget(self.ovpVolLabelS_ch3, 10, 15, 1, 1)
        self.ovpVolTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpVolTF_ch3.setObjectName("ovpVolTF_ch3")
        self.gridLayout_2.addWidget(self.ovpVolTF_ch3, 10, 14, 1, 1)
        self.ovpVolSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ovpVolSP_ch3.setObjectName("ovpVolSP_ch3")
        self.gridLayout_2.addWidget(self.ovpVolSP_ch3, 10, 16, 1, 1)
        self.ovpStateLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelS_ch3.setObjectName("ovpStateLabelS_ch3")
        self.gridLayout_2.addWidget(self.ovpStateLabelS_ch3, 9, 15, 1, 1)
        self.ovpStateBttn_ch3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ovpStateBttn_ch3.setObjectName("ovpStateBttn_ch3")
        self.gridLayout_2.addWidget(self.ovpStateBttn_ch3, 9, 16, 1, 1)
        self.ocpStateTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpStateTF_ch1.setObjectName("ocpStateTF_ch1")
        self.gridLayout_2.addWidget(self.ocpStateTF_ch1, 13, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 12, 2, 1, 1)
        self.ocpStateLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelR_ch1.setObjectName("ocpStateLabelR_ch1")
        self.gridLayout_2.addWidget(self.ocpStateLabelR_ch1, 13, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 12, 13, 1, 1)
        self.ocpCurrLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelR_ch1.setObjectName("ocpCurrLabelR_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrLabelR_ch1, 14, 2, 1, 1)
        self.ocpCurrTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpCurrTF_ch1.setObjectName("ocpCurrTF_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrTF_ch1, 14, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 12, 7, 1, 1)
        self.ocpCurrSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ocpCurrSP_ch1.setObjectName("ocpCurrSP_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrSP_ch1, 14, 5, 1, 1)
        self.ocpStateBttn_ch1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ocpStateBttn_ch1.setObjectName("ocpStateBttn_ch1")
        self.gridLayout_2.addWidget(self.ocpStateBttn_ch1, 13, 5, 1, 1)
        self.ocpStateLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelS_ch1.setObjectName("ocpStateLabelS_ch1")
        self.gridLayout_2.addWidget(self.ocpStateLabelS_ch1, 13, 4, 1, 1)
        self.ocpCurrLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelS_ch1.setObjectName("ocpCurrLabelS_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrLabelS_ch1, 14, 4, 1, 1)
        self.ocpStateLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelR_ch2.setObjectName("ocpStateLabelR_ch2")
        self.gridLayout_2.addWidget(self.ocpStateLabelR_ch2, 13, 7, 1, 1)
        self.ocpStateLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelS_ch2.setObjectName("ocpStateLabelS_ch2")
        self.gridLayout_2.addWidget(self.ocpStateLabelS_ch2, 13, 9, 1, 1)
        self.ocpCurrTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpCurrTF_ch2.setObjectName("ocpCurrTF_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrTF_ch2, 14, 8, 1, 1)
        self.ocpStateTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpStateTF_ch2.setObjectName("ocpStateTF_ch2")
        self.gridLayout_2.addWidget(self.ocpStateTF_ch2, 13, 8, 1, 1)
        self.ocpStateBttn_ch2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ocpStateBttn_ch2.setObjectName("ocpStateBttn_ch2")
        self.gridLayout_2.addWidget(self.ocpStateBttn_ch2, 13, 11, 1, 1)
        self.ocpCurrLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelS_ch2.setObjectName("ocpCurrLabelS_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrLabelS_ch2, 14, 9, 1, 1)
        self.ocpCurrLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelR_ch2.setObjectName("ocpCurrLabelR_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrLabelR_ch2, 14, 7, 1, 1)
        self.uploadfileTF = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.uploadfileTF.setObjectName("uploadfileTF")
        self.gridLayout_2.addWidget(self.uploadfileTF, 2, 2, 1, 1)
        self.ocpCurrSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ocpCurrSP_ch2.setObjectName("ocpCurrSP_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrSP_ch2, 14, 11, 1, 1)
        self.ocpStateLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelR_ch3.setObjectName("ocpStateLabelR_ch3")
        self.gridLayout_2.addWidget(self.ocpStateLabelR_ch3, 13, 13, 1, 1)
        self.ocpCurrLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelR_ch3.setObjectName("ocpCurrLabelR_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrLabelR_ch3, 14, 13, 1, 1)
        self.ocpCurrLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelS_ch3.setObjectName("ocpCurrLabelS_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrLabelS_ch3, 14, 15, 1, 1)
        self.ocpStateTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpStateTF_ch3.setObjectName("ocpStateTF_ch3")
        self.gridLayout_2.addWidget(self.ocpStateTF_ch3, 13, 14, 1, 1)
        self.ocpStateLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelS_ch3.setObjectName("ocpStateLabelS_ch3")
        self.gridLayout_2.addWidget(self.ocpStateLabelS_ch3, 13, 15, 1, 1)
        self.ocpStateBttn_ch3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ocpStateBttn_ch3.setObjectName("ocpStateBttn_ch3")
        self.gridLayout_2.addWidget(self.ocpStateBttn_ch3, 13, 16, 1, 1)
        self.ocpCurrSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ocpCurrSP_ch3.setObjectName("ocpCurrSP_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrSP_ch3, 14, 16, 1, 1)
        self.ocpCurrTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpCurrTF_ch3.setObjectName("ocpCurrTF_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrTF_ch3, 14, 14, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 7, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 11, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 9, 6, 1, 1)
        self.applySelectedBttn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.applySelectedBttn.setObjectName("applySelectedBttn")
        self.gridLayout_2.addWidget(self.applySelectedBttn, 3, 16, 1, 1)
        self.switchBttn_channels = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.switchBttn_channels.setObjectName("switchBttn_channels")
        self.gridLayout_2.addWidget(self.switchBttn_channels, 3, 15, 1, 1)
        self.saveAsBttn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveAsBttn.setObjectName("saveAsBttn")
        self.gridLayout_2.addWidget(self.saveAsBttn, 2, 4, 1, 1)
        self.browseBttn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browseBttn.setObjectName("browseBttn")
        self.gridLayout_2.addWidget(self.browseBttn, 2, 3, 1, 1)

        self.voltageLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelR_ch1.setObjectName("voltageLabelR_ch1")
        self.gridLayout_2.addWidget(self.voltageLabelR_ch1, 5, 2, 1, 1)
        self.channel1_rBttn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.channel1_rBttn.setObjectName("channel1_rBttn")
        self.gridLayout_2.addWidget(self.channel1_rBttn, 3, 2, 1, 1)
        self.setStateBttn_ch1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.setStateBttn_ch1.setObjectName("setStateBttn_ch1")
        self.gridLayout_2.addWidget(self.setStateBttn_ch1, 4, 5, 1, 1)
        self.stateLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelR_ch1.setObjectName("stateLabelR_ch1")
        self.gridLayout_2.addWidget(self.stateLabelR_ch1, 4, 2, 1, 1)
        self.statetReadingField_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.statetReadingField_ch1.setObjectName("statetReadingField_ch1")
        self.gridLayout_2.addWidget(self.statetReadingField_ch1, 4, 3, 1, 1)
        self.stateLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelS_ch1.setObjectName("stateLabelS_ch1")
        self.gridLayout_2.addWidget(self.stateLabelS_ch1, 4, 4, 1, 1)
        self.ovpStateTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpStateTF_ch3.setObjectName("ovpStateTF_ch3")
        self.gridLayout_2.addWidget(self.ovpStateTF_ch3, 9, 14, 1, 1)
        self.channel2_rBttn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.channel2_rBttn.setObjectName("channel2_rBttn")
        self.gridLayout_2.addWidget(self.channel2_rBttn, 3, 7, 1, 1)
        self.channel3_rBttn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.channel3_rBttn.setObjectName("channel3_rBttn")
        self.gridLayout_2.addWidget(self.channel3_rBttn, 3, 13, 1, 1)
        self.ovpVolLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelR_ch3.setObjectName("ovpVolLabelR_ch3")
        self.gridLayout_2.addWidget(self.ovpVolLabelR_ch3, 10, 13, 1, 1)
        self.voltageLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelS_ch1.setObjectName("voltageLabelS_ch1")
        self.gridLayout_2.addWidget(self.voltageLabelS_ch1, 5, 4, 1, 1)
        self.ovpStateBttn_ch2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ovpStateBttn_ch2.setObjectName("ovpStateBttn_ch2")
        self.gridLayout_2.addWidget(self.ovpStateBttn_ch2, 9, 11, 1, 1)
        self.ovpVolSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ovpVolSP_ch2.setObjectName("ovpVolSP_ch2")
        self.gridLayout_2.addWidget(self.ovpVolSP_ch2, 10, 11, 1, 1)
        self.ovpVolLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelS_ch2.setObjectName("ovpVolLabelS_ch2")
        self.gridLayout_2.addWidget(self.ovpVolLabelS_ch2, 10, 9, 1, 1)
        self.currentLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelS_ch1.setObjectName("currentLabelS_ch1")
        self.gridLayout_2.addWidget(self.currentLabelS_ch1, 6, 4, 1, 1)
        self.currentSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.currentSP_ch1.setObjectName("currentSP_ch1")
        self.gridLayout_2.addWidget(self.currentSP_ch1, 6, 5, 1, 1)
        self.voltageLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelR_ch3.setObjectName("voltageLabelR_ch3")
        self.gridLayout_2.addWidget(self.voltageLabelR_ch3, 5, 13, 1, 1)
        self.currentReadingField_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentReadingField_ch1.setObjectName("currentReadingField_ch1")
        self.gridLayout_2.addWidget(self.currentReadingField_ch1, 6, 3, 1, 1)
        self.voltageSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.voltageSP_ch1.setObjectName("voltageSP_ch1")
        self.gridLayout_2.addWidget(self.voltageSP_ch1, 5, 5, 1, 1)
        self.currentLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelR_ch2.setObjectName("currentLabelR_ch2")
        self.gridLayout_2.addWidget(self.currentLabelR_ch2, 6, 7, 1, 1)
        self.currentLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelR_ch1.setObjectName("currentLabelR_ch1")
        self.gridLayout_2.addWidget(self.currentLabelR_ch1, 6, 2, 1, 1)
        self.voltageLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelR_ch2.setObjectName("voltageLabelR_ch2")
        self.gridLayout_2.addWidget(self.voltageLabelR_ch2, 5, 7, 1, 1)
        self.statetReadingField_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.statetReadingField_ch2.setObjectName("statetReadingField_ch2")
        self.gridLayout_2.addWidget(self.statetReadingField_ch2, 4, 8, 1, 1)
        self.stateLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelR_ch2.setObjectName("stateLabelR_ch2")
        self.gridLayout_2.addWidget(self.stateLabelR_ch2, 4, 7, 1, 1)
        self.setStateBttn_ch2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.setStateBttn_ch2.setObjectName("setStateBttn_ch2")
        self.gridLayout_2.addWidget(self.setStateBttn_ch2, 4, 11, 1, 1)
        self.currentReadingField_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentReadingField_ch2.setObjectName("currentReadingField_ch2")
        self.gridLayout_2.addWidget(self.currentReadingField_ch2, 6, 8, 1, 1)
        self.voltageReadingField_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.voltageReadingField_ch2.setObjectName("voltageReadingField_ch2")
        self.gridLayout_2.addWidget(self.voltageReadingField_ch2, 5, 8, 1, 1)
        self.voltageLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelS_ch2.setObjectName("voltageLabelS_ch2")
        self.gridLayout_2.addWidget(self.voltageLabelS_ch2, 5, 9, 1, 1)
        self.currentLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelS_ch2.setObjectName("currentLabelS_ch2")
        self.gridLayout_2.addWidget(self.currentLabelS_ch2, 6, 9, 1, 1)
        self.voltageSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.voltageSP_ch2.setObjectName("voltageSP_ch2")
        self.gridLayout_2.addWidget(self.voltageSP_ch2, 5, 11, 1, 1)
        self.currentSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.currentSP_ch2.setObjectName("currentSP_ch2")
        self.gridLayout_2.addWidget(self.currentSP_ch2, 6, 11, 1, 1)
        self.stateLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelS_ch2.setObjectName("stateLabelS_ch2")
        self.gridLayout_2.addWidget(self.stateLabelS_ch2, 4, 9, 1, 1)
        self.stateLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelR_ch3.setObjectName("stateLabelR_ch3")
        self.gridLayout_2.addWidget(self.stateLabelR_ch3, 4, 13, 1, 1)
        self.currentLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelR_ch3.setObjectName("currentLabelR_ch3")
        self.gridLayout_2.addWidget(self.currentLabelR_ch3, 6, 13, 1, 1)
        self.voltageReadingField_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.voltageReadingField_ch3.setObjectName("voltageReadingField_ch3")
        self.gridLayout_2.addWidget(self.voltageReadingField_ch3, 5, 14, 1, 1)
        self.statetReadingField_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.statetReadingField_ch3.setObjectName("statetReadingField_ch3")
        self.gridLayout_2.addWidget(self.statetReadingField_ch3, 4, 14, 1, 1)
        self.currentReadingField_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentReadingField_ch3.setObjectName("currentReadingField_ch3")
        self.gridLayout_2.addWidget(self.currentReadingField_ch3, 6, 14, 1, 1)
        self.voltageSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.voltageSP_ch3.setObjectName("voltageSP_ch3")
        self.gridLayout_2.addWidget(self.voltageSP_ch3, 5, 16, 1, 1)
        self.stateLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelS_ch3.setObjectName("stateLabelS_ch3")
        self.gridLayout_2.addWidget(self.stateLabelS_ch3, 4, 15, 1, 1)
        self.voltageLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelS_ch3.setObjectName("voltageLabelS_ch3")
        self.gridLayout_2.addWidget(self.voltageLabelS_ch3, 5, 15, 1, 1)
        self.setStateBttn_ch3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.setStateBttn_ch3.setObjectName("setStateBttn_ch3")
        self.gridLayout_2.addWidget(self.setStateBttn_ch3, 4, 16, 1, 1)
        self.currentLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelS_ch3.setObjectName("currentLabelS_ch3")
        self.gridLayout_2.addWidget(self.currentLabelS_ch3, 6, 15, 1, 1)
        self.currentSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.currentSP_ch3.setObjectName("currentSP_ch3")
        self.gridLayout_2.addWidget(self.currentSP_ch3, 6, 16, 1, 1)
        self.ovpStateBttn_ch1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ovpStateBttn_ch1.setObjectName("ovpStateBttn_ch1")
        self.gridLayout_2.addWidget(self.ovpStateBttn_ch1, 9, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 13, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 8, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 8, 2, 1, 1)
        self.ovpStateTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpStateTF_ch1.setObjectName("ovpStateTF_ch1")
        self.gridLayout_2.addWidget(self.ovpStateTF_ch1, 9, 3, 1, 1)
        self.ovpStateLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelS_ch1.setObjectName("ovpStateLabelS_ch1")
        self.gridLayout_2.addWidget(self.ovpStateLabelS_ch1, 9, 4, 1, 1)
        self.ovpStateLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelR_ch2.setObjectName("ovpStateLabelR_ch2")
        self.gridLayout_2.addWidget(self.ovpStateLabelR_ch2, 9, 7, 1, 1)
        self.ovpStateLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelR_ch1.setObjectName("ovpStateLabelR_ch1")
        self.gridLayout_2.addWidget(self.ovpStateLabelR_ch1, 9, 2, 1, 1)
        self.ovpVolTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpVolTF_ch1.setObjectName("ovpVolTF_ch1")
        self.gridLayout_2.addWidget(self.ovpVolTF_ch1, 10, 3, 1, 1)
        self.ovpVolLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelR_ch1.setObjectName("ovpVolLabelR_ch1")
        self.gridLayout_2.addWidget(self.ovpVolLabelR_ch1, 10, 2, 1, 1)
        self.ovpVolLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelR_ch2.setObjectName("ovpVolLabelR_ch2")
        self.gridLayout_2.addWidget(self.ovpVolLabelR_ch2, 10, 7, 1, 1)
        self.ovpStateTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpStateTF_ch2.setObjectName("ovpStateTF_ch2")
        self.gridLayout_2.addWidget(self.ovpStateTF_ch2, 9, 8, 1, 1)
        self.ovpVolSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ovpVolSP_ch1.setObjectName("ovpVolSP_ch1")
        self.gridLayout_2.addWidget(self.ovpVolSP_ch1, 10, 5, 1, 1)
        self.ovpVolTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpVolTF_ch2.setObjectName("ovpVolTF_ch2")
        self.gridLayout_2.addWidget(self.ovpVolTF_ch2, 10, 8, 1, 1)
        self.ovpVolLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelS_ch1.setObjectName("ovpVolLabelS_ch1")
        self.gridLayout_2.addWidget(self.ovpVolLabelS_ch1, 10, 4, 1, 1)
        self.ovpStateLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelS_ch2.setObjectName("ovpStateLabelS_ch2")
        self.gridLayout_2.addWidget(self.ovpStateLabelS_ch2, 9, 9, 1, 1)
        self.ovpStateLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelR_ch3.setObjectName("ovpStateLabelR_ch3")
        self.gridLayout_2.addWidget(self.ovpStateLabelR_ch3, 9, 13, 1, 1)
        self.setBttn_ch1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setBttn_ch1.setObjectName("setBttn_ch1")
        self.gridLayout_2.addWidget(self.setBttn_ch1, 15, 2, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 9, 12, 1, 1)
        self.setBttn_ch2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setBttn_ch2.setObjectName("setBttn_ch2")
        self.gridLayout_2.addWidget(self.setBttn_ch2, 15, 7, 1, 5)
        self.setBttn_ch3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setBttn_ch3.setObjectName("setBttn_ch3")
        self.gridLayout_2.addWidget(self.setBttn_ch3, 15, 13, 1, 4)
        self.plotGV_ch3 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plotGV_ch3.setObjectName("plotGV_ch3")
        self.gridLayout_2.addWidget(self.plotGV_ch3, 16, 13, 1, 4)
        self.plotGV_ch2 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plotGV_ch2.setObjectName("plotGV_ch2")
        self.gridLayout_2.addWidget(self.plotGV_ch2, 16, 7, 1, 5)
        self.plotGV_ch1 = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents)
        self.plotGV_ch1.setObjectName("plotGV_ch1")
        self.gridLayout_2.addWidget(self.plotGV_ch1, 16, 2, 1, 4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1270, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ovpVolLabelS_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpStateLabelS_ch3.setText(_translate("MainWindow", "State"))
        self.ovpStateBttn_ch3.setText(_translate("MainWindow", "ON"))
        self.label_5.setText(_translate("MainWindow", "Overcurrent Protection"))
        self.ocpStateLabelR_ch1.setText(_translate("MainWindow", "State"))
        self.label_7.setText(_translate("MainWindow", "Overcurrent Protection"))
        self.ocpCurrLabelR_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.label_6.setText(_translate("MainWindow", "Overcurrent Protection"))
        self.ocpStateBttn_ch1.setText(_translate("MainWindow", "ON"))
        self.ocpStateLabelS_ch1.setText(_translate("MainWindow", "State"))
        self.ocpCurrLabelS_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateLabelR_ch2.setText(_translate("MainWindow", "State"))
        self.ocpStateLabelS_ch2.setText(_translate("MainWindow", "State"))
        self.ocpStateBttn_ch2.setText(_translate("MainWindow", "ON"))
        self.ocpCurrLabelS_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.ocpCurrLabelR_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateLabelR_ch3.setText(_translate("MainWindow", "State"))
        self.ocpCurrLabelR_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.ocpCurrLabelS_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateLabelS_ch3.setText(_translate("MainWindow", "State"))
        self.ocpStateBttn_ch3.setText(_translate("MainWindow", "ON"))
        self.applySelectedBttn.setText(_translate("MainWindow", "Apply Selected"))
        self.switchBttn_channels.setText(_translate("MainWindow", "Switch ON/OFF"))
        self.saveAsBttn.setText(_translate("MainWindow", "Save As Preset"))
        self.browseBttn.setText(_translate("MainWindow", "Browse"))
        self.voltageLabelR_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.channel1_rBttn.setText(_translate("MainWindow", "Channel 1"))
        self.setStateBttn_ch1.setText(_translate("MainWindow", "ON"))
        self.stateLabelR_ch1.setText(_translate("MainWindow", "State"))
        self.stateLabelS_ch1.setText(_translate("MainWindow", "State"))
        self.channel2_rBttn.setText(_translate("MainWindow", "Channel 2"))
        self.channel3_rBttn.setText(_translate("MainWindow", "Channel 3"))
        self.ovpVolLabelR_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.voltageLabelS_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpStateBttn_ch2.setText(_translate("MainWindow", "ON"))
        self.ovpVolLabelS_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.currentLabelS_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.voltageLabelR_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.currentLabelR_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.currentLabelR_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.voltageLabelR_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.stateLabelR_ch2.setText(_translate("MainWindow", "State"))
        self.setStateBttn_ch2.setText(_translate("MainWindow", "ON"))
        self.voltageLabelS_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.currentLabelS_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.stateLabelS_ch2.setText(_translate("MainWindow", "State"))
        self.stateLabelR_ch3.setText(_translate("MainWindow", "State"))
        self.currentLabelR_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.stateLabelS_ch3.setText(_translate("MainWindow", "State"))
        self.voltageLabelS_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.setStateBttn_ch3.setText(_translate("MainWindow", "ON"))
        self.currentLabelS_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.ovpStateBttn_ch1.setText(_translate("MainWindow", "ON"))
        self.label_4.setText(_translate("MainWindow", "Overvoltage Protection"))
        self.label_3.setText(_translate("MainWindow", "Overvoltage Protection"))
        self.label_2.setText(_translate("MainWindow", "Overvoltage Protection"))
        self.ovpStateLabelS_ch1.setText(_translate("MainWindow", "State"))
        self.ovpStateLabelR_ch2.setText(_translate("MainWindow", "State"))
        self.ovpStateLabelR_ch1.setText(_translate("MainWindow", "State"))
        self.ovpVolLabelR_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpVolLabelR_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpVolLabelS_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpStateLabelS_ch2.setText(_translate("MainWindow", "State"))
        self.ovpStateLabelR_ch3.setText(_translate("MainWindow", "State"))
        self.setBttn_ch1.setText(_translate("MainWindow", "Set"))
        self.setBttn_ch2.setText(_translate("MainWindow", "Set"))
        self.setBttn_ch3.setText(_translate("MainWindow", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

