# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
   def setupUi(self, MainWindow):
       MainWindow.setObjectName("MainWindow")
       MainWindow.resize(945, 738)
       self.centralwidget = QtWidgets.QWidget(MainWindow)
       self.centralwidget.setObjectName("centralwidget")
       self.channel1_rBttn = QtWidgets.QRadioButton(self.centralwidget)
       self.channel1_rBttn.setGeometry(QtCore.QRect(10, 30, 117, 22))
       self.channel1_rBttn.setObjectName("channel1_rBttn")
       self.channel2_rBttn = QtWidgets.QRadioButton(self.centralwidget)
       self.channel2_rBttn.setGeometry(QtCore.QRect(140, 30, 117, 22))
       self.channel2_rBttn.setObjectName("channel2_rBttn")
       self.channel3_rBttn = QtWidgets.QRadioButton(self.centralwidget)
       self.channel3_rBttn.setGeometry(QtCore.QRect(270, 30, 117, 22))
       self.channel3_rBttn.setObjectName("channel3_rBttn")
       self.switchBttn_channels = QtWidgets.QPushButton(self.centralwidget)
       self.switchBttn_channels.setGeometry(QtCore.QRect(380, 20, 121, 31))
       self.switchBttn_channels.setObjectName("switchBttn_channels")
       self.applySelectedBttn = QtWidgets.QPushButton(self.centralwidget)
       self.applySelectedBttn.setGeometry(QtCore.QRect(380, 60, 121, 31))
       self.applySelectedBttn.setObjectName("applySelectedBttn")
       self.channel1GB = QtWidgets.QGroupBox(self.centralwidget)
       self.channel1GB.setGeometry(QtCore.QRect(10, 100, 301, 581))
       self.channel1GB.setObjectName("channel1GB")
       self.stateLabelR_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.stateLabelR_ch1.setGeometry(QtCore.QRect(0, 30, 41, 17))
       self.stateLabelR_ch1.setObjectName("stateLabelR_ch1")
       self.voltageLabelR_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.voltageLabelR_ch1.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.voltageLabelR_ch1.setObjectName("voltageLabelR_ch1")
       self.currentLabelR_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.currentLabelR_ch1.setGeometry(QtCore.QRect(0, 90, 81, 17))
       self.currentLabelR_ch1.setObjectName("currentLabelR_ch1")
       self.statetReadingField_ch1 = QtWidgets.QLineEdit(self.channel1GB)
       self.statetReadingField_ch1.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.statetReadingField_ch1.setObjectName("statetReadingField_ch1")
       self.voltageReadingField_ch1 = QtWidgets.QLineEdit(self.channel1GB)
       self.voltageReadingField_ch1.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.voltageReadingField_ch1.setObjectName("voltageReadingField_ch1")
       self.currentReadingField_ch1 = QtWidgets.QLineEdit(self.channel1GB)
       self.currentReadingField_ch1.setGeometry(QtCore.QRect(80, 90, 41, 27))
       self.currentReadingField_ch1.setObjectName("currentReadingField_ch1")
       self.currentLabelS_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.currentLabelS_ch1.setGeometry(QtCore.QRect(130, 90, 81, 17))
       self.currentLabelS_ch1.setObjectName("currentLabelS_ch1")
       self.stateLabelS_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.stateLabelS_ch1.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.stateLabelS_ch1.setObjectName("stateLabelS_ch1")
       self.voltageLabelS_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.voltageLabelS_ch1.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.voltageLabelS_ch1.setObjectName("voltageLabelS_ch1")
       self.currentSP_ch1 = QtWidgets.QDoubleSpinBox(self.channel1GB)
       self.currentSP_ch1.setGeometry(QtCore.QRect(220, 90, 69, 27))
       self.currentSP_ch1.setObjectName("currentSP_ch1")
       self.voltageSP_ch1 = QtWidgets.QDoubleSpinBox(self.channel1GB)
       self.voltageSP_ch1.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.voltageSP_ch1.setObjectName("voltageSP_ch1")
       self.setStateBttn_ch1 = QtWidgets.QRadioButton(self.channel1GB)
       self.setStateBttn_ch1.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.setStateBttn_ch1.setObjectName("setStateBttn_ch1")
       self.ovpGB_ch1 = QtWidgets.QGroupBox(self.channel1GB)
       self.ovpGB_ch1.setGeometry(QtCore.QRect(0, 130, 291, 91))
       self.ovpGB_ch1.setObjectName("ovpGB_ch1")
       self.ovpVolTF_ch1 = QtWidgets.QLineEdit(self.ovpGB_ch1)
       self.ovpVolTF_ch1.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.ovpVolTF_ch1.setObjectName("ovpVolTF_ch1")
       self.ovpStateLabelS_ch1 = QtWidgets.QLabel(self.ovpGB_ch1)
       self.ovpStateLabelS_ch1.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.ovpStateLabelS_ch1.setObjectName("ovpStateLabelS_ch1")
       self.ovpStateLabelR_ch1 = QtWidgets.QLabel(self.ovpGB_ch1)
       self.ovpStateLabelR_ch1.setGeometry(QtCore.QRect(0, 30, 41, 17))
       self.ovpStateLabelR_ch1.setObjectName("ovpStateLabelR_ch1")
       self.ovpStateBttn_ch1 = QtWidgets.QRadioButton(self.ovpGB_ch1)
       self.ovpStateBttn_ch1.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.ovpStateBttn_ch1.setObjectName("ovpStateBttn_ch1")
       self.ovpVolLabelR_ch1 = QtWidgets.QLabel(self.ovpGB_ch1)
       self.ovpVolLabelR_ch1.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.ovpVolLabelR_ch1.setObjectName("ovpVolLabelR_ch1")
       self.ovpVolSP_ch1 = QtWidgets.QDoubleSpinBox(self.ovpGB_ch1)
       self.ovpVolSP_ch1.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.ovpVolSP_ch1.setObjectName("ovpVolSP_ch1")
       self.ovpVolLabelS_ch1 = QtWidgets.QLabel(self.ovpGB_ch1)
       self.ovpVolLabelS_ch1.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.ovpVolLabelS_ch1.setObjectName("ovpVolLabelS_ch1")
       self.ovpStateTF_ch1 = QtWidgets.QLineEdit(self.ovpGB_ch1)
       self.ovpStateTF_ch1.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.ovpStateTF_ch1.setObjectName("ovpStateTF_ch1")
       self.ocpGB_ch1 = QtWidgets.QGroupBox(self.channel1GB)
       self.ocpGB_ch1.setGeometry(QtCore.QRect(0, 230, 291, 91))
       self.ocpGB_ch1.setObjectName("ocpGB_ch1")
       self.ocpCurrTF_ch1 = QtWidgets.QLineEdit(self.ocpGB_ch1)
       self.ocpCurrTF_ch1.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.ocpCurrTF_ch1.setObjectName("ocpCurrTF_ch1")
       self.ocpStateLabelS_ch1 = QtWidgets.QLabel(self.ocpGB_ch1)
       self.ocpStateLabelS_ch1.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.ocpStateLabelS_ch1.setObjectName("ocpStateLabelS_ch1")
       self.ocpStateLabelR_ch1 = QtWidgets.QLabel(self.ocpGB_ch1)
       self.ocpStateLabelR_ch1.setGeometry(QtCore.QRect(0, 30, 67, 17))
       self.ocpStateLabelR_ch1.setObjectName("ocpStateLabelR_ch1")
       self.ocpStateBttn_ch1 = QtWidgets.QRadioButton(self.ocpGB_ch1)
       self.ocpStateBttn_ch1.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.ocpStateBttn_ch1.setObjectName("ocpStateBttn_ch1")
       self.ocpCurrLabelR_ch1 = QtWidgets.QLabel(self.ocpGB_ch1)
       self.ocpCurrLabelR_ch1.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.ocpCurrLabelR_ch1.setObjectName("ocpCurrLabelR_ch1")
       self.ocpCurrSP_ch1 = QtWidgets.QDoubleSpinBox(self.ocpGB_ch1)
       self.ocpCurrSP_ch1.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.ocpCurrSP_ch1.setObjectName("ocpCurrSP_ch1")
       self.ocpCurrLabelS_ch1 = QtWidgets.QLabel(self.ocpGB_ch1)
       self.ocpCurrLabelS_ch1.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.ocpCurrLabelS_ch1.setObjectName("ocpCurrLabelS_ch1")
       self.ocpStateTF_ch1 = QtWidgets.QLineEdit(self.ocpGB_ch1)
       self.ocpStateTF_ch1.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.ocpStateTF_ch1.setObjectName("ocpStateTF_ch1")
       self.setBttn_ch1 = QtWidgets.QPushButton(self.channel1GB)
       self.setBttn_ch1.setGeometry(QtCore.QRect(0, 330, 291, 27))
       self.setBttn_ch1.setObjectName("setBttn_ch1")
       self.plotlabel_ch1 = QtWidgets.QLabel(self.channel1GB)
       self.plotlabel_ch1.setGeometry(QtCore.QRect(0, 370, 67, 17))
       self.plotlabel_ch1.setObjectName("plotlabel_ch1")
       self.plotGV_ch1 = QtWidgets.QGraphicsView(self.channel1GB)
       self.plotGV_ch1.setGeometry(QtCore.QRect(20, 390, 256, 181))
       self.plotGV_ch1.setObjectName("plotGV_ch1")
       self.browsePreset_GB = QtWidgets.QGroupBox(self.centralwidget)
       self.browsePreset_GB.setGeometry(QtCore.QRect(590, 9, 311, 81))
       self.browsePreset_GB.setObjectName("browsePreset_GB")
       self.browseBttn = QtWidgets.QPushButton(self.browsePreset_GB)
       self.browseBttn.setGeometry(QtCore.QRect(0, 50, 99, 27))
       self.browseBttn.setObjectName("browseBttn")
       self.loadBttn = QtWidgets.QPushButton(self.browsePreset_GB)
       self.loadBttn.setGeometry(QtCore.QRect(100, 50, 99, 27))
       self.loadBttn.setObjectName("loadBttn")
       self.saveAsBttn = QtWidgets.QPushButton(self.browsePreset_GB)
       self.saveAsBttn.setGeometry(QtCore.QRect(200, 50, 111, 27))
       self.saveAsBttn.setObjectName("saveAsBttn")
       self.temp_uploadfileTF = QtWidgets.QLineEdit(self.browsePreset_GB)
       self.temp_uploadfileTF.setGeometry(QtCore.QRect(10, 26, 171, 21))
       self.temp_uploadfileTF.setObjectName("temp_uploadfileTF")
       self.channel2GB = QtWidgets.QGroupBox(self.centralwidget)
       self.channel2GB.setGeometry(QtCore.QRect(320, 100, 301, 581))
       self.channel2GB.setObjectName("channel2GB")
       self.stateLabelR_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.stateLabelR_ch2.setGeometry(QtCore.QRect(0, 30, 41, 17))
       self.stateLabelR_ch2.setObjectName("stateLabelR_ch2")
       self.voltageLabelR_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.voltageLabelR_ch2.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.voltageLabelR_ch2.setObjectName("voltageLabelR_ch2")
       self.currentLabelR_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.currentLabelR_ch2.setGeometry(QtCore.QRect(0, 90, 81, 17))
       self.currentLabelR_ch2.setObjectName("currentLabelR_ch2")
       self.statetReadingField_ch2 = QtWidgets.QLineEdit(self.channel2GB)
       self.statetReadingField_ch2.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.statetReadingField_ch2.setObjectName("statetReadingField_ch2")
       self.voltageReadingField_ch2 = QtWidgets.QLineEdit(self.channel2GB)
       self.voltageReadingField_ch2.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.voltageReadingField_ch2.setObjectName("voltageReadingField_ch2")
       self.currentReadingField_ch2 = QtWidgets.QLineEdit(self.channel2GB)
       self.currentReadingField_ch2.setGeometry(QtCore.QRect(80, 90, 41, 27))
       self.currentReadingField_ch2.setObjectName("currentReadingField_ch2")
       self.currentLabelS_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.currentLabelS_ch2.setGeometry(QtCore.QRect(130, 90, 81, 17))
       self.currentLabelS_ch2.setObjectName("currentLabelS_ch2")
       self.stateLabelS_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.stateLabelS_ch2.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.stateLabelS_ch2.setObjectName("stateLabelS_ch2")
       self.voltageLabelS_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.voltageLabelS_ch2.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.voltageLabelS_ch2.setObjectName("voltageLabelS_ch2")
       self.currentSP_ch2 = QtWidgets.QDoubleSpinBox(self.channel2GB)
       self.currentSP_ch2.setGeometry(QtCore.QRect(220, 90, 69, 27))
       self.currentSP_ch2.setObjectName("currentSP_ch2")
       self.voltageSP_ch2 = QtWidgets.QDoubleSpinBox(self.channel2GB)
       self.voltageSP_ch2.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.voltageSP_ch2.setObjectName("voltageSP_ch2")
       self.setStateBttn_ch2 = QtWidgets.QRadioButton(self.channel2GB)
       self.setStateBttn_ch2.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.setStateBttn_ch2.setObjectName("setStateBttn_ch2")
       self.ovpGB_ch2 = QtWidgets.QGroupBox(self.channel2GB)
       self.ovpGB_ch2.setGeometry(QtCore.QRect(0, 130, 291, 91))
       self.ovpGB_ch2.setObjectName("ovpGB_ch2")
       self.ovpVolTF_ch2 = QtWidgets.QLineEdit(self.ovpGB_ch2)
       self.ovpVolTF_ch2.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.ovpVolTF_ch2.setObjectName("ovpVolTF_ch2")
       self.ovpStateLabelS_ch2 = QtWidgets.QLabel(self.ovpGB_ch2)
       self.ovpStateLabelS_ch2.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.ovpStateLabelS_ch2.setObjectName("ovpStateLabelS_ch2")
       self.ovpStateLabelR_ch2 = QtWidgets.QLabel(self.ovpGB_ch2)
       self.ovpStateLabelR_ch2.setGeometry(QtCore.QRect(0, 30, 41, 17))
       self.ovpStateLabelR_ch2.setObjectName("ovpStateLabelR_ch2")
       self.ovpStateBttn_ch2 = QtWidgets.QRadioButton(self.ovpGB_ch2)
       self.ovpStateBttn_ch2.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.ovpStateBttn_ch2.setObjectName("ovpStateBttn_ch2")
       self.ovpVolLabelR_ch2 = QtWidgets.QLabel(self.ovpGB_ch2)
       self.ovpVolLabelR_ch2.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.ovpVolLabelR_ch2.setObjectName("ovpVolLabelR_ch2")
       self.ovpVolSP_ch2 = QtWidgets.QDoubleSpinBox(self.ovpGB_ch2)
       self.ovpVolSP_ch2.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.ovpVolSP_ch2.setObjectName("ovpVolSP_ch2")
       self.ovpVolLabelS_ch2 = QtWidgets.QLabel(self.ovpGB_ch2)
       self.ovpVolLabelS_ch2.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.ovpVolLabelS_ch2.setObjectName("ovpVolLabelS_ch2")
       self.ovpStateTF_ch2 = QtWidgets.QLineEdit(self.ovpGB_ch2)
       self.ovpStateTF_ch2.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.ovpStateTF_ch2.setObjectName("ovpStateTF_ch2")
       self.ocpGB_ch2 = QtWidgets.QGroupBox(self.channel2GB)
       self.ocpGB_ch2.setGeometry(QtCore.QRect(0, 230, 291, 91))
       self.ocpGB_ch2.setObjectName("ocpGB_ch2")
       self.ocpCurrTF_ch2 = QtWidgets.QLineEdit(self.ocpGB_ch2)
       self.ocpCurrTF_ch2.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.ocpCurrTF_ch2.setObjectName("ocpCurrTF_ch2")
       self.ocpStateLabelS_ch2 = QtWidgets.QLabel(self.ocpGB_ch2)
       self.ocpStateLabelS_ch2.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.ocpStateLabelS_ch2.setObjectName("ocpStateLabelS_ch2")
       self.ocpStateLabelR_ch2 = QtWidgets.QLabel(self.ocpGB_ch2)
       self.ocpStateLabelR_ch2.setGeometry(QtCore.QRect(0, 30, 67, 17))
       self.ocpStateLabelR_ch2.setObjectName("ocpStateLabelR_ch2")
       self.ocpStateBttn_ch2 = QtWidgets.QRadioButton(self.ocpGB_ch2)
       self.ocpStateBttn_ch2.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.ocpStateBttn_ch2.setObjectName("ocpStateBttn_ch2")
       self.ocpCurrLabelR_ch2 = QtWidgets.QLabel(self.ocpGB_ch2)
       self.ocpCurrLabelR_ch2.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.ocpCurrLabelR_ch2.setObjectName("ocpCurrLabelR_ch2")
       self.ocpCurrSP_ch2 = QtWidgets.QDoubleSpinBox(self.ocpGB_ch2)
       self.ocpCurrSP_ch2.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.ocpCurrSP_ch2.setObjectName("ocpCurrSP_ch2")
       self.ocpCurrLabelS_ch2 = QtWidgets.QLabel(self.ocpGB_ch2)
       self.ocpCurrLabelS_ch2.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.ocpCurrLabelS_ch2.setObjectName("ocpCurrLabelS_ch2")
       self.ocpStateTF_ch2 = QtWidgets.QLineEdit(self.ocpGB_ch2)
       self.ocpStateTF_ch2.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.ocpStateTF_ch2.setObjectName("ocpStateTF_ch2")
       self.setBttn_ch2 = QtWidgets.QPushButton(self.channel2GB)
       self.setBttn_ch2.setGeometry(QtCore.QRect(0, 330, 291, 27))
       self.setBttn_ch2.setObjectName("setBttn_ch2")
       self.plotlabel_ch2 = QtWidgets.QLabel(self.channel2GB)
       self.plotlabel_ch2.setGeometry(QtCore.QRect(0, 370, 67, 17))
       self.plotlabel_ch2.setObjectName("plotlabel_ch2")
       self.plotGV_ch2 = QtWidgets.QGraphicsView(self.channel2GB)
       self.plotGV_ch2.setGeometry(QtCore.QRect(20, 390, 256, 181))
       self.plotGV_ch2.setObjectName("plotGV_ch2")
       self.channel3GB = QtWidgets.QGroupBox(self.centralwidget)
       self.channel3GB.setGeometry(QtCore.QRect(630, 100, 301, 581))
       self.channel3GB.setObjectName("channel3GB")
       self.stateLabelR_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.stateLabelR_ch3.setGeometry(QtCore.QRect(0, 30, 41, 17))
       self.stateLabelR_ch3.setObjectName("stateLabelR_ch3")
       self.voltageLabelR_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.voltageLabelR_ch3.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.voltageLabelR_ch3.setObjectName("voltageLabelR_ch3")
       self.currentLabelR_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.currentLabelR_ch3.setGeometry(QtCore.QRect(0, 90, 81, 17))
       self.currentLabelR_ch3.setObjectName("currentLabelR_ch3")
       self.statetReadingField_ch3 = QtWidgets.QLineEdit(self.channel3GB)
       self.statetReadingField_ch3.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.statetReadingField_ch3.setObjectName("statetReadingField_ch3")
       self.voltageReadingField_ch3 = QtWidgets.QLineEdit(self.channel3GB)
       self.voltageReadingField_ch3.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.voltageReadingField_ch3.setObjectName("voltageReadingField_ch3")
       self.currentReadingField_ch3 = QtWidgets.QLineEdit(self.channel3GB)
       self.currentReadingField_ch3.setGeometry(QtCore.QRect(80, 90, 41, 27))
       self.currentReadingField_ch3.setObjectName("currentReadingField_ch3")
       self.currentLabelS_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.currentLabelS_ch3.setGeometry(QtCore.QRect(130, 90, 81, 17))
       self.currentLabelS_ch3.setObjectName("currentLabelS_ch3")
       self.stateLabelS_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.stateLabelS_ch3.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.stateLabelS_ch3.setObjectName("stateLabelS_ch3")
       self.voltageLabelS_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.voltageLabelS_ch3.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.voltageLabelS_ch3.setObjectName("voltageLabelS_ch3")
       self.currentSP_ch3 = QtWidgets.QDoubleSpinBox(self.channel3GB)
       self.currentSP_ch3.setGeometry(QtCore.QRect(220, 90, 69, 27))
       self.currentSP_ch3.setObjectName("currentSP_ch3")
       self.voltageSP_ch3 = QtWidgets.QDoubleSpinBox(self.channel3GB)
       self.voltageSP_ch3.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.voltageSP_ch3.setObjectName("voltageSP_ch3")
       self.setStateBttn_ch3 = QtWidgets.QRadioButton(self.channel3GB)
       self.setStateBttn_ch3.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.setStateBttn_ch3.setObjectName("setStateBttn_ch3")
       self.ovpGB_ch3 = QtWidgets.QGroupBox(self.channel3GB)
       self.ovpGB_ch3.setGeometry(QtCore.QRect(0, 130, 291, 91))
       self.ovpGB_ch3.setObjectName("ovpGB_ch3")
       self.ovpVolTF_ch3 = QtWidgets.QLineEdit(self.ovpGB_ch3)
       self.ovpVolTF_ch3.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.ovpVolTF_ch3.setObjectName("ovpVolTF_ch3")
       self.ovpStateLabelS_ch3 = QtWidgets.QLabel(self.ovpGB_ch3)
       self.ovpStateLabelS_ch3.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.ovpStateLabelS_ch3.setObjectName("ovpStateLabelS_ch3")
       self.ovpStateLabelR_ch3 = QtWidgets.QLabel(self.ovpGB_ch3)
       self.ovpStateLabelR_ch3.setGeometry(QtCore.QRect(0, 30, 41, 17))
       self.ovpStateLabelR_ch3.setObjectName("ovpStateLabelR_ch3")
       self.ovpStateBttn_ch3 = QtWidgets.QRadioButton(self.ovpGB_ch3)
       self.ovpStateBttn_ch3.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.ovpStateBttn_ch3.setObjectName("ovpStateBttn_ch3")
       self.ovpVolLabelR_ch3 = QtWidgets.QLabel(self.ovpGB_ch3)
       self.ovpVolLabelR_ch3.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.ovpVolLabelR_ch3.setObjectName("ovpVolLabelR_ch3")
       self.ovpVolSP_ch3 = QtWidgets.QDoubleSpinBox(self.ovpGB_ch3)
       self.ovpVolSP_ch3.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.ovpVolSP_ch3.setObjectName("ovpVolSP_ch3")
       self.ovpVolLabelS_ch3 = QtWidgets.QLabel(self.ovpGB_ch3)
       self.ovpVolLabelS_ch3.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.ovpVolLabelS_ch3.setObjectName("ovpVolLabelS_ch3")
       self.ovpStateTF_ch3 = QtWidgets.QLineEdit(self.ovpGB_ch3)
       self.ovpStateTF_ch3.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.ovpStateTF_ch3.setObjectName("ovpStateTF_ch3")
       self.ocpGB_ch3 = QtWidgets.QGroupBox(self.channel3GB)
       self.ocpGB_ch3.setGeometry(QtCore.QRect(0, 230, 291, 91))
       self.ocpGB_ch3.setObjectName("ocpGB_ch3")
       self.ocpCurrTF_ch3 = QtWidgets.QLineEdit(self.ocpGB_ch3)
       self.ocpCurrTF_ch3.setGeometry(QtCore.QRect(80, 60, 41, 27))
       self.ocpCurrTF_ch3.setObjectName("ocpCurrTF_ch3")
       self.ocpStateLabelS_ch3 = QtWidgets.QLabel(self.ocpGB_ch3)
       self.ocpStateLabelS_ch3.setGeometry(QtCore.QRect(130, 30, 67, 17))
       self.ocpStateLabelS_ch3.setObjectName("ocpStateLabelS_ch3")
       self.ocpStateLabelR_ch3 = QtWidgets.QLabel(self.ocpGB_ch3)
       self.ocpStateLabelR_ch3.setGeometry(QtCore.QRect(0, 30, 67, 17))
       self.ocpStateLabelR_ch3.setObjectName("ocpStateLabelR_ch3")
       self.ocpStateBttn_ch3 = QtWidgets.QRadioButton(self.ocpGB_ch3)
       self.ocpStateBttn_ch3.setGeometry(QtCore.QRect(226, 30, 61, 22))
       self.ocpStateBttn_ch3.setObjectName("ocpStateBttn_ch3")
       self.ocpCurrLabelR_ch3 = QtWidgets.QLabel(self.ocpGB_ch3)
       self.ocpCurrLabelR_ch3.setGeometry(QtCore.QRect(0, 60, 81, 17))
       self.ocpCurrLabelR_ch3.setObjectName("ocpCurrLabelR_ch3")
       self.ocpCurrSP_ch3 = QtWidgets.QDoubleSpinBox(self.ocpGB_ch3)
       self.ocpCurrSP_ch3.setGeometry(QtCore.QRect(220, 60, 69, 27))
       self.ocpCurrSP_ch3.setObjectName("ocpCurrSP_ch3")
       self.ocpCurrLabelS_ch3 = QtWidgets.QLabel(self.ocpGB_ch3)
       self.ocpCurrLabelS_ch3.setGeometry(QtCore.QRect(130, 60, 81, 17))
       self.ocpCurrLabelS_ch3.setObjectName("ocpCurrLabelS_ch3")
       self.ocpStateTF_ch3 = QtWidgets.QLineEdit(self.ocpGB_ch3)
       self.ocpStateTF_ch3.setGeometry(QtCore.QRect(40, 30, 81, 27))
       self.ocpStateTF_ch3.setObjectName("ocpStateTF_ch3")
       self.setBttn_ch3 = QtWidgets.QPushButton(self.channel3GB)
       self.setBttn_ch3.setGeometry(QtCore.QRect(0, 330, 291, 27))
       self.setBttn_ch3.setObjectName("setBttn_ch3")
       self.plotlabel_ch3 = QtWidgets.QLabel(self.channel3GB)
       self.plotlabel_ch3.setGeometry(QtCore.QRect(0, 370, 67, 17))
       self.plotlabel_ch3.setObjectName("plotlabel_ch3")
       self.plotGV_ch3 = QtWidgets.QGraphicsView(self.channel3GB)
       self.plotGV_ch3.setGeometry(QtCore.QRect(20, 390, 256, 181))
       self.plotGV_ch3.setObjectName("plotGV_ch3")
       MainWindow.setCentralWidget(self.centralwidget)
       self.menubar = QtWidgets.QMenuBar(MainWindow)
       self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 25))
       self.menubar.setObjectName("menubar")
       MainWindow.setMenuBar(self.menubar)
       self.statusbar = QtWidgets.QStatusBar(MainWindow)
       self.statusbar.setObjectName("statusbar")
       MainWindow.setStatusBar(self.statusbar)

       self.retranslateUi(MainWindow)
       QtCore.QMetaObject.connectSlotsByName(MainWindow)

   def retranslateUi(self, MainWindow):
       _translate = QtCore.QCoreApplication.translate
       MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
       self.channel1_rBttn.setText(_translate("MainWindow", "Channel 1"))
       self.channel2_rBttn.setText(_translate("MainWindow", "Channel 2"))
       self.channel3_rBttn.setText(_translate("MainWindow", "Channel 3"))
       self.switchBttn_channels.setText(_translate("MainWindow", "Switch ON/OFF"))
       self.applySelectedBttn.setText(_translate("MainWindow", "Apply Selected"))
       self.channel1GB.setTitle(_translate("MainWindow", "Channel 1"))
       self.stateLabelR_ch1.setText(_translate("MainWindow", "State"))
       self.voltageLabelR_ch1.setText(_translate("MainWindow", "Voltage (V)"))
       self.currentLabelR_ch1.setText(_translate("MainWindow", "Current (A)"))
       self.currentLabelS_ch1.setText(_translate("MainWindow", "Current (A)"))
       self.stateLabelS_ch1.setText(_translate("MainWindow", "State"))
       self.voltageLabelS_ch1.setText(_translate("MainWindow", "Voltage (V)"))
       self.setStateBttn_ch1.setText(_translate("MainWindow", "ON"))
       self.ovpGB_ch1.setTitle(_translate("MainWindow", "Overvoltage Protection"))
       self.ovpStateLabelS_ch1.setText(_translate("MainWindow", "State"))
       self.ovpStateLabelR_ch1.setText(_translate("MainWindow", "State"))
       self.ovpStateBttn_ch1.setText(_translate("MainWindow", "ON"))
       self.ovpVolLabelR_ch1.setText(_translate("MainWindow", "Voltage (V)"))
       self.ovpVolLabelS_ch1.setText(_translate("MainWindow", "Voltage (V)"))
       self.ocpGB_ch1.setTitle(_translate("MainWindow", "Overcurrent Protection"))
       self.ocpStateLabelS_ch1.setText(_translate("MainWindow", "State"))
       self.ocpStateLabelR_ch1.setText(_translate("MainWindow", "State"))
       self.ocpStateBttn_ch1.setText(_translate("MainWindow", "ON"))
       self.ocpCurrLabelR_ch1.setText(_translate("MainWindow", "Current (A)"))
       self.ocpCurrLabelS_ch1.setText(_translate("MainWindow", "Current (A)"))
       self.setBttn_ch1.setText(_translate("MainWindow", "Set"))
       self.plotlabel_ch1.setText(_translate("MainWindow", "Plot"))
       self.browsePreset_GB.setTitle(_translate("MainWindow", "Browse Preset"))
       self.browseBttn.setText(_translate("MainWindow", "Browse"))
       self.loadBttn.setText(_translate("MainWindow", "Load"))
       self.saveAsBttn.setText(_translate("MainWindow", "Save As Preset"))
       self.temp_uploadfileTF.setText(_translate("MainWindow", "Upload file here"))
       self.channel2GB.setTitle(_translate("MainWindow", "Channel 2"))
       self.stateLabelR_ch2.setText(_translate("MainWindow", "State"))
       self.voltageLabelR_ch2.setText(_translate("MainWindow", "Voltage (V)"))
       self.currentLabelR_ch2.setText(_translate("MainWindow", "Current (A)"))
       self.currentLabelS_ch2.setText(_translate("MainWindow", "Current (A)"))
       self.stateLabelS_ch2.setText(_translate("MainWindow", "State"))
       self.voltageLabelS_ch2.setText(_translate("MainWindow", "Voltage (V)"))
       self.setStateBttn_ch2.setText(_translate("MainWindow", "ON"))
       self.ovpGB_ch2.setTitle(_translate("MainWindow", "Overvoltage Protection"))
       self.ovpStateLabelS_ch2.setText(_translate("MainWindow", "State"))
       self.ovpStateLabelR_ch2.setText(_translate("MainWindow", "State"))
       self.ovpStateBttn_ch2.setText(_translate("MainWindow", "ON"))
       self.ovpVolLabelR_ch2.setText(_translate("MainWindow", "Voltage (V)"))
       self.ovpVolLabelS_ch2.setText(_translate("MainWindow", "Voltage (V)"))
       self.ocpGB_ch2.setTitle(_translate("MainWindow", "Overcurrent Protection"))
       self.ocpStateLabelS_ch2.setText(_translate("MainWindow", "State"))
       self.ocpStateLabelR_ch2.setText(_translate("MainWindow", "State"))
       self.ocpStateBttn_ch2.setText(_translate("MainWindow", "ON"))
       self.ocpCurrLabelR_ch2.setText(_translate("MainWindow", "Current (A)"))
       self.ocpCurrLabelS_ch2.setText(_translate("MainWindow", "Current (A)"))
       self.setBttn_ch2.setText(_translate("MainWindow", "Set"))
       self.plotlabel_ch2.setText(_translate("MainWindow", "Plot"))
       self.channel3GB.setTitle(_translate("MainWindow", "Channel 3"))
       self.stateLabelR_ch3.setText(_translate("MainWindow", "State"))
       self.voltageLabelR_ch3.setText(_translate("MainWindow", "Voltage (V)"))
       self.currentLabelR_ch3.setText(_translate("MainWindow", "Current (A)"))
       self.currentLabelS_ch3.setText(_translate("MainWindow", "Current (A)"))
       self.stateLabelS_ch3.setText(_translate("MainWindow", "State"))
       self.voltageLabelS_ch3.setText(_translate("MainWindow", "Voltage (V)"))
       self.setStateBttn_ch3.setText(_translate("MainWindow", "ON"))
       self.ovpGB_ch3.setTitle(_translate("MainWindow", "Overvoltage Protection"))
       self.ovpStateLabelS_ch3.setText(_translate("MainWindow", "State"))
       self.ovpStateLabelR_ch3.setText(_translate("MainWindow", "State"))
       self.ovpStateBttn_ch3.setText(_translate("MainWindow", "ON"))
       self.ovpVolLabelR_ch3.setText(_translate("MainWindow", "Voltage (V)"))
       self.ovpVolLabelS_ch3.setText(_translate("MainWindow", "Voltage (V)"))
       self.ocpGB_ch3.setTitle(_translate("MainWindow", "Overcurrent Protection"))
       self.ocpStateLabelS_ch3.setText(_translate("MainWindow", "State"))
       self.ocpStateLabelR_ch3.setText(_translate("MainWindow", "State"))
       self.ocpStateBttn_ch3.setText(_translate("MainWindow", "ON"))
       self.ocpCurrLabelR_ch3.setText(_translate("MainWindow", "Current (A)"))
       self.ocpCurrLabelS_ch3.setText(_translate("MainWindow", "Current (A)"))
       self.setBttn_ch3.setText(_translate("MainWindow", "Set"))
       self.plotlabel_ch3.setText(_translate("MainWindow", "Plot"))


if __name__ == "__main__":
   import sys
   app = QtWidgets.QApplication(sys.argv)
   MainWindow = QtWidgets.QMainWindow()
   ui = Ui_MainWindow()
   ui.setupUi(MainWindow)
   MainWindow.show()
   sys.exit(app.exec_())


