# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!
# This code was generated after creating the UI using PyQt
# it shows the Window name and font configuration
# as well as the Objects such as Text Fields and Buttons configuration

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("DP832 Controller")
        MainWindow.resize(674, 831)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1399, 737))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ocpCurrSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ocpCurrSP_ch1.setObjectName("ocpCurrSP_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrSP_ch1, 16, 6, 1, 1)
        self.ovpStateBttn_ch3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ovpStateBttn_ch3.setObjectName("ovpStateBttn_ch3")
        self.gridLayout_2.addWidget(self.ovpStateBttn_ch3, 11, 21, 1, 1)
        self.ocpStateLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelR_ch1.setObjectName("ocpStateLabelR_ch1")
        self.gridLayout_2.addWidget(self.ocpStateLabelR_ch1, 15, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 14, 9, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 14, 17, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 17, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 9, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 17, 1, 5)
        self.channel2_rBttn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.channel2_rBttn.setObjectName("channel2_rBttn")
        self.gridLayout_2.addWidget(self.channel2_rBttn, 2, 10, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 3, 16, 14, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 3, 2, 1, 6)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 3, 9, 1, 7)
        self.channel1_rBttn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.channel1_rBttn.setObjectName("channel1_rBttn")
        self.gridLayout_2.addWidget(self.channel1_rBttn, 2, 9, 1, 1)
        self.channel3_rBttn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.channel3_rBttn.setObjectName("channel3_rBttn")
        self.gridLayout_2.addWidget(self.channel3_rBttn, 2, 12, 1, 1)
        self.uploadfileTF = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.uploadfileTF.setObjectName("uploadfileTF")
        self.uploadfileTF.setReadOnly(True)
        self.gridLayout_2.addWidget(self.uploadfileTF, 2, 2, 1, 1)
        self.ocpCurrSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ocpCurrSP_ch2.setObjectName("ocpCurrSP_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrSP_ch2, 16, 14, 1, 1)
        self.ocpStateLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelR_ch3.setObjectName("ocpStateLabelR_ch3")
        self.gridLayout_2.addWidget(self.ocpStateLabelR_ch3, 15, 17, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 3, 8, 14, 1)
        self.ocpCurrLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelR_ch3.setObjectName("ocpCurrLabelR_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrLabelR_ch3, 16, 17, 1, 1)
        self.ocpCurrSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ocpCurrSP_ch3.setObjectName("ocpCurrSP_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrSP_ch3, 16, 21, 1, 1)
        self.ocpCurrLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelS_ch3.setObjectName("ocpCurrLabelS_ch3")
        self.gridLayout_2.addWidget(self.ocpCurrLabelS_ch3, 16, 20, 1, 1)
        self.ocpStateTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpStateTF_ch3.setObjectName("ocpStateTF_ch3")
        self.ocpStateTF_ch3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ocpStateTF_ch3, 15, 18, 1, 1)
        self.ocpStateBttn_ch3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ocpStateBttn_ch3.setObjectName("ocpStateBttn_ch3")
        self.gridLayout_2.addWidget(self.ocpStateBttn_ch3, 15, 21, 1, 1)
        self.ocpCurrLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelR_ch2.setObjectName("ocpCurrLabelR_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrLabelR_ch2, 16, 9, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 9, 2, 1, 1)
        self.ocpCurrTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpCurrTF_ch3.setObjectName("ocpCurrTF_ch3")
        self.ocpCurrTF_ch3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ocpCurrTF_ch3, 16, 18, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 11, 7, 1, 1)
        self.ocpStateLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelS_ch3.setObjectName("ocpStateLabelS_ch3")
        self.gridLayout_2.addWidget(self.ocpStateLabelS_ch3, 15, 20, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 13, 2, 1, 1)
        self.switchBttn_channels = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.switchBttn_channels.setObjectName("switchBttn_channels")
        self.gridLayout_2.addWidget(self.switchBttn_channels, 2, 17, 1, 1)
        self.saveAsBttn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.saveAsBttn.setObjectName("saveAsBttn")
        self.gridLayout_2.addWidget(self.saveAsBttn, 2, 5, 1, 1)
        self.ovpVolLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelS_ch3.setObjectName("ovpVolLabelS_ch3")
        self.gridLayout_2.addWidget(self.ovpVolLabelS_ch3, 12, 20, 1, 1)
        self.ovpStateLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelS_ch3.setObjectName("ovpStateLabelS_ch3")
        self.gridLayout_2.addWidget(self.ovpStateLabelS_ch3, 11, 20, 1, 1)
        self.voltageReadingField_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.voltageReadingField_ch1.setObjectName("voltageReadingField_ch1")
        self.voltageReadingField_ch1.setReadOnly(True)
        self.gridLayout_2.addWidget(self.voltageReadingField_ch1, 7, 3, 1, 1)
        self.ovpVolSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ovpVolSP_ch3.setObjectName("ovpVolSP_ch3")
        self.gridLayout_2.addWidget(self.ovpVolSP_ch3, 12, 21, 1, 1)
        self.ovpVolTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpVolTF_ch3.setObjectName("ovpVolTF_ch3")
        self.ovpVolTF_ch3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ovpVolTF_ch3, 12, 18, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 14, 2, 1, 1)
        self.ocpStateTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpStateTF_ch1.setObjectName("ocpStateTF_ch1")
        self.ocpStateTF_ch1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ocpStateTF_ch1, 15, 3, 1, 1)
        self.setStateBttn_ch3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.setStateBttn_ch3.setObjectName("setStateBttn_ch3")
        self.gridLayout_2.addWidget(self.setStateBttn_ch3, 6, 21, 1, 1)
        self.ovpStateBttn_ch1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ovpStateBttn_ch1.setObjectName("ovpStateBttn_ch1")
        self.gridLayout_2.addWidget(self.ovpStateBttn_ch1, 11, 6, 1, 1)
        self.currentReadingField_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentReadingField_ch3.setObjectName("currentReadingField_ch3")
        self.currentReadingField_ch3.setReadOnly(True)
        self.gridLayout_2.addWidget(self.currentReadingField_ch3, 8, 18, 1, 1)
        self.voltageSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.voltageSP_ch3.setObjectName("voltageSP_ch3")
        self.gridLayout_2.addWidget(self.voltageSP_ch3, 7, 21, 1, 1)
        self.voltageLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelS_ch3.setObjectName("voltageLabelS_ch3")
        self.gridLayout_2.addWidget(self.voltageLabelS_ch3, 7, 20, 1, 1)
        self.ocpCurrLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelR_ch1.setObjectName("ocpCurrLabelR_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrLabelR_ch1, 16, 2, 1, 1)
        self.ocpStateLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelS_ch2.setObjectName("ocpStateLabelS_ch2")
        self.gridLayout_2.addWidget(self.ocpStateLabelS_ch2, 15, 12, 1, 1)
        self.ocpCurrTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpCurrTF_ch1.setObjectName("ocpCurrTF_ch1")
        self.ocpCurrTF_ch1.setReadOnly(True)
        self.gridLayout_2.addWidget(self.ocpCurrTF_ch1, 16, 3, 1, 1)
        self.ocpStateLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelS_ch1.setObjectName("ocpStateLabelS_ch1")
        self.gridLayout_2.addWidget(self.ocpStateLabelS_ch1, 15, 5, 1, 1)
        self.ocpStateLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpStateLabelR_ch2.setObjectName("ocpStateLabelR_ch2")
        self.gridLayout_2.addWidget(self.ocpStateLabelR_ch2, 15, 9, 1, 1)
        self.ocpStateTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpStateTF_ch2.setObjectName("ocpStateTF_ch2")
        self.ocpStateTF_ch2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ocpStateTF_ch2, 15, 10, 1, 1)
        self.ocpCurrLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelS_ch1.setObjectName("ocpCurrLabelS_ch1")
        self.gridLayout_2.addWidget(self.ocpCurrLabelS_ch1, 16, 5, 1, 1)
        self.ocpStateBttn_ch1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ocpStateBttn_ch1.setObjectName("ocpStateBttn_ch1")
        self.gridLayout_2.addWidget(self.ocpStateBttn_ch1, 15, 6, 1, 1)
        self.ocpCurrLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ocpCurrLabelS_ch2.setObjectName("ocpCurrLabelS_ch2")
        self.gridLayout_2.addWidget(self.ocpCurrLabelS_ch2, 16, 12, 1, 1)
        self.ovpVolTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpVolTF_ch1.setObjectName("ovpVolTF_ch1")
        self.ovpVolTF_ch1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ovpVolTF_ch1, 12, 3, 1, 1)
        self.ovpStateLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelR_ch2.setObjectName("ovpStateLabelR_ch2")
        self.gridLayout_2.addWidget(self.ovpStateLabelR_ch2, 11, 9, 1, 1)
        self.ovpStateLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelR_ch1.setObjectName("ovpStateLabelR_ch1")
        self.gridLayout_2.addWidget(self.ovpStateLabelR_ch1, 11, 2, 1, 1)
        self.ocpCurrTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ocpCurrTF_ch2.setObjectName("ocpCurrTF_ch2")
        self.ocpCurrTF_ch2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ocpCurrTF_ch2, 16, 10, 1, 1)
        self.ocpStateBttn_ch2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ocpStateBttn_ch2.setObjectName("ocpStateBttn_ch2")
        self.gridLayout_2.addWidget(self.ocpStateBttn_ch2, 15, 14, 1, 1)
        self.ovpVolLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelR_ch2.setObjectName("ovpVolLabelR_ch2")
        self.gridLayout_2.addWidget(self.ovpVolLabelR_ch2, 12, 9, 1, 1)
        self.ovpVolLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelR_ch1.setObjectName("ovpVolLabelR_ch1")
        self.gridLayout_2.addWidget(self.ovpVolLabelR_ch1, 12, 2, 1, 1)
        self.ovpVolTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpVolTF_ch2.setObjectName("ovpVolTF_ch2")
        self.ovpVolTF_ch2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ovpVolTF_ch2, 12, 10, 1, 1)
        self.ovpVolSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ovpVolSP_ch1.setObjectName("ovpVolSP_ch1")
        self.gridLayout_2.addWidget(self.ovpVolSP_ch1, 12, 6, 1, 1)
        self.ovpStateLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelS_ch2.setObjectName("ovpStateLabelS_ch2")
        self.gridLayout_2.addWidget(self.ovpStateLabelS_ch2, 11, 12, 1, 1)
        self.stateLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelS_ch1.setObjectName("stateLabelS_ch1")
        self.gridLayout_2.addWidget(self.stateLabelS_ch1, 6, 5, 1, 1)
        self.ovpVolLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelS_ch1.setObjectName("ovpVolLabelS_ch1")
        self.gridLayout_2.addWidget(self.ovpVolLabelS_ch1, 12, 5, 1, 1)
        self.ovpStateTF_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpStateTF_ch2.setObjectName("ovpStateTF_ch2")
        self.ovpStateTF_ch2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ovpStateTF_ch2, 11, 10, 1, 1)
        self.voltageLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelR_ch1.setObjectName("voltageLabelR_ch1")
        self.gridLayout_2.addWidget(self.voltageLabelR_ch1, 7, 2, 1, 1)
        self.browseBttn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browseBttn.setObjectName("browseBttn")
        self.gridLayout_2.addWidget(self.browseBttn, 2, 3, 1, 1)
        self.setStateBttn_ch1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.setStateBttn_ch1.setObjectName("setStateBttn_ch1")
        self.gridLayout_2.addWidget(self.setStateBttn_ch1, 6, 6, 1, 1)
        self.stateLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelR_ch1.setObjectName("stateLabelR_ch1")
        self.gridLayout_2.addWidget(self.stateLabelR_ch1, 6, 2, 1, 1)
        self.statetReadingField_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.statetReadingField_ch1.setObjectName("statetReadingField_ch1")
        self.statetReadingField_ch1.setReadOnly(True)
        self.gridLayout_2.addWidget(self.statetReadingField_ch1, 6, 3, 1, 1)
        self.voltageLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelS_ch1.setObjectName("voltageLabelS_ch1")
        self.gridLayout_2.addWidget(self.voltageLabelS_ch1, 7, 5, 1, 1)
        self.ovpStateTF_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpStateTF_ch3.setObjectName("ovpStateTF_ch3")
        self.ovpStateTF_ch3.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ovpStateTF_ch3, 11, 18, 1, 1)
        self.currentLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelS_ch1.setObjectName("currentLabelS_ch1")
        self.gridLayout_2.addWidget(self.currentLabelS_ch1, 8, 5, 1, 1)
        self.ovpVolLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelR_ch3.setObjectName("ovpVolLabelR_ch3")
        self.gridLayout_2.addWidget(self.ovpVolLabelR_ch3, 12, 17, 1, 1)
        self.ovpVolSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.ovpVolSP_ch2.setObjectName("ovpVolSP_ch2")
        self.gridLayout_2.addWidget(self.ovpVolSP_ch2, 12, 14, 1, 1)
        self.currentSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.currentSP_ch1.setObjectName("currentSP_ch1")
        self.gridLayout_2.addWidget(self.currentSP_ch1, 8, 6, 1, 1)
        self.ovpStateBttn_ch2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.ovpStateBttn_ch2.setObjectName("ovpStateBttn_ch2")
        self.gridLayout_2.addWidget(self.ovpStateBttn_ch2, 11, 14, 1, 1)
        self.currentLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelR_ch2.setObjectName("currentLabelR_ch2")
        self.gridLayout_2.addWidget(self.currentLabelR_ch2, 8, 9, 1, 1)
        self.ovpVolLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpVolLabelS_ch2.setObjectName("ovpVolLabelS_ch2")
        self.gridLayout_2.addWidget(self.ovpVolLabelS_ch2, 12, 12, 1, 1)
        self.voltageLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelR_ch3.setObjectName("voltageLabelR_ch3")
        self.gridLayout_2.addWidget(self.voltageLabelR_ch3, 7, 17, 1, 1)
        self.voltageSP_ch1 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.voltageSP_ch1.setObjectName("voltageSP_ch1")
        self.gridLayout_2.addWidget(self.voltageSP_ch1, 7, 6, 1, 1)
        self.currentReadingField_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentReadingField_ch1.setObjectName("currentReadingField_ch1")
        self.currentReadingField_ch1.setReadOnly(True)
        self.gridLayout_2.addWidget(self.currentReadingField_ch1, 8, 3, 1, 1)
        self.voltageLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelR_ch2.setObjectName("voltageLabelR_ch2")
        self.gridLayout_2.addWidget(self.voltageLabelR_ch2, 7, 9, 1, 1)
        self.currentReadingField_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.currentReadingField_ch2.setObjectName("currentReadingField_ch2")
        self.currentReadingField_ch2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.currentReadingField_ch2, 8, 10, 1, 1)
        self.stateLabelR_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelR_ch2.setObjectName("stateLabelR_ch2")
        self.gridLayout_2.addWidget(self.stateLabelR_ch2, 6, 9, 1, 1)
        self.currentLabelR_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelR_ch1.setObjectName("currentLabelR_ch1")
        self.gridLayout_2.addWidget(self.currentLabelR_ch1, 8, 2, 1, 1)
        self.voltageReadingField_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.voltageReadingField_ch2.setObjectName("voltageReadingField_ch2")
        self.voltageReadingField_ch2.setReadOnly(True)

        self.gridLayout_2.addWidget(self.voltageReadingField_ch2, 7, 10, 1, 1)
        self.statetReadingField_ch2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.statetReadingField_ch2.setObjectName("statetReadingField_ch2")
        self.statetReadingField_ch2.setReadOnly(True)
        self.gridLayout_2.addWidget(self.statetReadingField_ch2, 6, 10, 1, 1)
        self.currentLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelS_ch2.setObjectName("currentLabelS_ch2")
        self.gridLayout_2.addWidget(self.currentLabelS_ch2, 8, 12, 1, 1)
        self.setStateBttn_ch2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.setStateBttn_ch2.setObjectName("setStateBttn_ch2")
        self.gridLayout_2.addWidget(self.setStateBttn_ch2, 6, 14, 1, 1)
        self.voltageSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.voltageSP_ch2.setObjectName("voltageSP_ch2")
        self.gridLayout_2.addWidget(self.voltageSP_ch2, 7, 14, 1, 1)
        self.statetReadingField_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.statetReadingField_ch3.setObjectName("statetReadingField_ch3")
        self.statetReadingField_ch3.setReadOnly(True)
        self.gridLayout_2.addWidget(self.statetReadingField_ch3, 6, 18, 1, 1)
        self.voltageReadingField_ch3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.voltageReadingField_ch3.setObjectName("voltageReadingField_ch3")
        self.voltageReadingField_ch3.setReadOnly(True)
        self.gridLayout_2.addWidget(self.voltageReadingField_ch3, 7, 18, 1, 1)
        self.currentSP_ch2 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.currentSP_ch2.setObjectName("currentSP_ch2")
        self.gridLayout_2.addWidget(self.currentSP_ch2, 8, 14, 1, 1)
        self.stateLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelR_ch3.setObjectName("stateLabelR_ch3")
        self.gridLayout_2.addWidget(self.stateLabelR_ch3, 6, 17, 1, 1)
        self.voltageLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.voltageLabelS_ch2.setObjectName("voltageLabelS_ch2")
        self.gridLayout_2.addWidget(self.voltageLabelS_ch2, 7, 12, 1, 1)
        self.currentLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelR_ch3.setObjectName("currentLabelR_ch3")
        self.gridLayout_2.addWidget(self.currentLabelR_ch3, 8, 17, 1, 1)
        self.stateLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelS_ch3.setObjectName("stateLabelS_ch3")
        self.gridLayout_2.addWidget(self.stateLabelS_ch3, 6, 20, 1, 1)
        self.stateLabelS_ch2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.stateLabelS_ch2.setObjectName("stateLabelS_ch2")
        self.gridLayout_2.addWidget(self.stateLabelS_ch2, 6, 12, 1, 1)
        self.currentLabelS_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.currentLabelS_ch3.setObjectName("currentLabelS_ch3")
        self.gridLayout_2.addWidget(self.currentLabelS_ch3, 8, 20, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 10, 17, 1, 1)
        self.ovpStateLabelS_ch1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelS_ch1.setObjectName("ovpStateLabelS_ch1")
        self.gridLayout_2.addWidget(self.ovpStateLabelS_ch1, 11, 5, 1, 1)
        self.currentSP_ch3 = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.currentSP_ch3.setObjectName("currentSP_ch3")
        self.gridLayout_2.addWidget(self.currentSP_ch3, 8, 21, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 10, 9, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 11, 15, 1, 1)
        self.ovpStateTF_ch1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ovpStateTF_ch1.setObjectName("ovpStateTF_ch1")
        self.ovpStateTF_ch1.setReadOnly(True)

        self.gridLayout_2.addWidget(self.ovpStateTF_ch1, 11, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 10, 2, 1, 1)
        self.ovpStateLabelR_ch3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.ovpStateLabelR_ch3.setObjectName("ovpStateLabelR_ch3")
        self.gridLayout_2.addWidget(self.ovpStateLabelR_ch3, 11, 17, 1, 1)
        self.setBttn_ch2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setBttn_ch2.setObjectName("setBttn_ch2")
        self.gridLayout_2.addWidget(self.setBttn_ch2, 17, 9, 1, 6)
        self.setBttn_ch1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setBttn_ch1.setObjectName("setBttn_ch1")
        self.gridLayout_2.addWidget(self.setBttn_ch1, 17, 2, 1, 5)
        self.plotGV_ch2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.plotGV_ch2.setObjectName("plotGV_ch2")
        self.gridLayout_2.addWidget(self.plotGV_ch2, 18, 9, 1, 6)
        self.plotGV_ch1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.plotGV_ch1.setObjectName("plotGV_ch1")
        self.gridLayout_2.addWidget(self.plotGV_ch1, 18, 2, 1, 5)
        self.setBttn_ch3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setBttn_ch3.setObjectName("setBttn_ch3")
        self.gridLayout_2.addWidget(self.setBttn_ch3, 17, 17, 1, 5)
        self.plotGV_ch3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.plotGV_ch3.setObjectName("plotGV_ch3")
        self.gridLayout_2.addWidget(self.plotGV_ch3, 18, 17, 1, 5)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 4, 11, 13, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 4, 19, 13, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 4, 4, 13, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 9, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 5, 17, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 12, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 5, 20, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 674, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ovpStateBttn_ch3.setText(_translate("MainWindow", "ON"))
        self.ocpStateLabelR_ch1.setText(_translate("MainWindow", "State"))
        self.label_6.setText(_translate("MainWindow", "Overcurrent Protection"))
        self.label_7.setText(_translate("MainWindow", "Overcurrent Protection"))
        self.label_9.setText(_translate("MainWindow", "Channel 3"))
        self.label.setText(_translate("MainWindow", "Channel 1"))
        self.label_8.setText(_translate("MainWindow", "Channel 2"))
        self.channel2_rBttn.setText(_translate("MainWindow", "Channel 2"))
        self.channel1_rBttn.setText(_translate("MainWindow", "Channel 1"))
        self.channel3_rBttn.setText(_translate("MainWindow", "Channel 3"))
        self.ocpStateLabelR_ch3.setText(_translate("MainWindow", "State"))
        self.ocpCurrLabelR_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.ocpCurrLabelS_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateBttn_ch3.setText(_translate("MainWindow", "ON"))
        self.ocpCurrLabelR_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateLabelS_ch3.setText(_translate("MainWindow", "State"))
        self.switchBttn_channels.setText(_translate("MainWindow", "Switch ON/OFF"))
        self.saveAsBttn.setText(_translate("MainWindow", "Save As Preset"))
        self.ovpVolLabelS_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpStateLabelS_ch3.setText(_translate("MainWindow", "State"))
        self.label_5.setText(_translate("MainWindow", "Overcurrent Protection"))
        self.setStateBttn_ch3.setText(_translate("MainWindow", "ON"))
        self.ovpStateBttn_ch1.setText(_translate("MainWindow", "ON"))
        self.voltageLabelS_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.ocpCurrLabelR_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateLabelS_ch2.setText(_translate("MainWindow", "State"))
        self.ocpStateLabelS_ch1.setText(_translate("MainWindow", "State"))
        self.ocpStateLabelR_ch2.setText(_translate("MainWindow", "State"))
        self.ocpCurrLabelS_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.ocpStateBttn_ch1.setText(_translate("MainWindow", "ON"))
        self.ocpCurrLabelS_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.ovpStateLabelR_ch2.setText(_translate("MainWindow", "State"))
        self.ovpStateLabelR_ch1.setText(_translate("MainWindow", "State"))
        self.ocpStateBttn_ch2.setText(_translate("MainWindow", "ON"))
        self.ovpVolLabelR_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpVolLabelR_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpStateLabelS_ch2.setText(_translate("MainWindow", "State"))
        self.stateLabelS_ch1.setText(_translate("MainWindow", "State"))
        self.ovpVolLabelS_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.voltageLabelR_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.browseBttn.setText(_translate("MainWindow", "Browse"))
        self.setStateBttn_ch1.setText(_translate("MainWindow", "ON"))
        self.stateLabelR_ch1.setText(_translate("MainWindow", "State"))
        self.voltageLabelS_ch1.setText(_translate("MainWindow", "Voltage (V)"))
        self.currentLabelS_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.ovpVolLabelR_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.ovpStateBttn_ch2.setText(_translate("MainWindow", "ON"))
        self.currentLabelR_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.ovpVolLabelS_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.voltageLabelR_ch3.setText(_translate("MainWindow", "Voltage (V)"))
        self.voltageLabelR_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.stateLabelR_ch2.setText(_translate("MainWindow", "State"))
        self.currentLabelR_ch1.setText(_translate("MainWindow", "Current (A)"))
        self.currentLabelS_ch2.setText(_translate("MainWindow", "Current (A)"))
        self.setStateBttn_ch2.setText(_translate("MainWindow", "ON"))
        self.stateLabelR_ch3.setText(_translate("MainWindow", "State"))
        self.voltageLabelS_ch2.setText(_translate("MainWindow", "Voltage (V)"))
        self.currentLabelR_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.stateLabelS_ch3.setText(_translate("MainWindow", "State"))
        self.stateLabelS_ch2.setText(_translate("MainWindow", "State"))
        self.currentLabelS_ch3.setText(_translate("MainWindow", "Current (A)"))
        self.label_4.setText(_translate("MainWindow", "Overvoltage Protection"))
        self.ovpStateLabelS_ch1.setText(_translate("MainWindow", "State"))
        self.label_3.setText(_translate("MainWindow", "Overvoltage Protection"))
        self.label_2.setText(_translate("MainWindow", "Overvoltage Protection"))
        self.ovpStateLabelR_ch3.setText(_translate("MainWindow", "State"))
        self.setBttn_ch2.setText(_translate("MainWindow", "Set"))
        self.setBttn_ch1.setText(_translate("MainWindow", "Set"))
        self.setBttn_ch3.setText(_translate("MainWindow", "Set"))
        self.label_11.setText(_translate("MainWindow", "Settings"))
        self.label_12.setText(_translate("MainWindow", "Readouts"))
        self.label_14.setText(_translate("MainWindow", "Readouts"))
        self.label_13.setText(_translate("MainWindow", "Settings"))
        self.label_15.setText(_translate("MainWindow", "Settings"))
        self.label_10.setText(_translate("MainWindow", "Readouts"))
        self.plotGV_ch1.setText(_translate("MainWindow", "View Plot"))
        self.plotGV_ch2.setText(_translate("MainWindow", "View Plot"))
        self.plotGV_ch3.setText(_translate("MainWindow", "View Plot"))
